import Foundation
import Testing
@testable import AuthBoxCrypto

/// Cross-platform consistency tests.
///
/// These test vectors were generated by running the TypeScript @authbox/crypto
/// with the same inputs. Every value must match byte-for-byte.
/// If any test fails, iOS and Web will produce different passwords
/// for the same seed — a catastrophic bug for a password manager.
@Suite("Cross-Platform Consistency")
struct CrossPlatformTests {

    // MARK: - Test Mnemonics (BIP-39 standard vectors)

    static let M12 = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
    static let M24 = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art"

    // MARK: - Seed Generation

    @Test("12-word mnemonic validates")
    func m12Valid() {
        #expect(Seed.validateMnemonic(Self.M12) == true)
    }

    @Test("24-word mnemonic validates")
    func m24Valid() {
        #expect(Seed.validateMnemonic(Self.M24) == true)
    }

    @Test("12-word mnemonic produces correct seed")
    func m12Seed() {
        let seed = Seed.mnemonicToSeed(Self.M12)
        let hex = seed.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4")
    }

    @Test("24-word mnemonic produces correct seed")
    func m24Seed() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let hex = seed.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "408b285c123836004f4b8842c89324c1f01382450c0d439af345ba7fc49acf705489c6fc77dbd4e3dc1dd8cc6bc9f043db8ada1e243c4a0eafb290d399480840")
    }

    // MARK: - HD Key Derivation

    @Test("vault key matches TypeScript")
    func vaultKey() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveKey(seed: seed, purpose: .vault, index: 0)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "fe8e595d1f0b35df7e40f53e0be546e0a4e7e53f604def8a79916a48579e51b6")
    }

    @Test("sync key matches TypeScript")
    func syncKey() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveKey(seed: seed, purpose: .sync, index: 0)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "8724f4c07bbdd1aff75daa6821393b9fc6bc2ac985f982128927c6c3b375a8c6")
    }

    @Test("agent key 0 matches TypeScript")
    func agentKey0() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveKey(seed: seed, purpose: .agent, index: 0)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "63b22dd2b72bebb6f235c11c4f5ea8d17aa1bd845ba53649cb5a661801adf999")
    }

    @Test("auth key matches TypeScript")
    func authKey() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveKey(seed: seed, purpose: .auth, index: 0)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "0e2fe1c64d4d042cd26c138a155668e65c0e57b80b057c4e30514e9b1cc4898b")
    }

    @Test("derive key 0 matches TypeScript")
    func deriveKey0() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveKey(seed: seed, purpose: .derive, index: 0)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "ca8843429edb8be13968f39a08c1ad9a5b3060e3259151e63fa765ee40eca27d")
    }

    @Test("agent key 1 matches TypeScript")
    func agentKey1() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveAgentKey(seed: seed, agentIndex: 1)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "317ed4289750dda7f2efcd08ac4835e14c5beb1f988bf109587988e10c8dd81c")
    }

    @Test("agent key 5 matches TypeScript")
    func agentKey5() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let key = Seed.deriveAgentKey(seed: seed, agentIndex: 5)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "fffa62b038554cc4231f7af8de8f7650c541375ffd90071db22ec24aba692e74")
    }

    // MARK: - HKDF Sub-Keys

    @Test("HKDF auth sub-key matches TypeScript")
    func hkdfAuth() {
        let masterKey = Data(0..<32)  // [0x00, 0x01, ..., 0x1f]
        let key = HKDFDerivation.deriveSubKey(masterKey: masterKey, purpose: .auth)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "a66799eaa946b3ca2ee72608f99bba1fe1e97f0f019eec11ab9baff32cf7fdd6")
    }

    @Test("HKDF enc sub-key matches TypeScript")
    func hkdfEnc() {
        let masterKey = Data(0..<32)
        let key = HKDFDerivation.deriveSubKey(masterKey: masterKey, purpose: .enc)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "b1f072227ccad830c1af298ba5835ed3c1100404e82ca8d75fa86e50a2430ea0")
    }

    @Test("HKDF mac sub-key matches TypeScript")
    func hkdfMac() {
        let masterKey = Data(0..<32)
        let key = HKDFDerivation.deriveSubKey(masterKey: masterKey, purpose: .mac)
        let hex = key.map { String(format: "%02x", $0) }.joined()
        #expect(hex == "57d4665d105b77b53fe5715a9d9fb9d53c9435814b9a39565343c0c7a221f6ad")
    }

    // MARK: - Deterministic Passwords

    @Test("password(github.com) matches TypeScript")
    func pwGithub() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let pw = Seed.derivePassword(seed: seed, site: "github.com")
        #expect(pw == "d$^ton](I(^8R{dprpi%")
    }

    @Test("password(google.com) matches TypeScript")
    func pwGoogle() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let pw = Seed.derivePassword(seed: seed, site: "google.com")
        #expect(pw == "D#}2Nu[$(cHb}ii44F3-")
    }

    @Test("password(github.com, counter=1) matches TypeScript")
    func pwGithubCounter1() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let pw = Seed.derivePassword(seed: seed, site: "github.com",
            options: DerivePasswordOptions(counter: 1))
        #expect(pw == "+JKp-h1l#r=i{uVa)vLR")
    }

    @Test("password is case-insensitive")
    func pwCaseInsensitive() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let pw1 = Seed.derivePassword(seed: seed, site: "github.com")
        let pw2 = Seed.derivePassword(seed: seed, site: "GitHub.com")
        #expect(pw1 == pw2)
        #expect(pw1 == "d$^ton](I(^8R{dprpi%")
    }

    @Test("password(test.com, lower-only, 32) matches TypeScript")
    func pwTestLower32() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let pw = Seed.derivePassword(seed: seed, site: "test.com",
            options: DerivePasswordOptions(
                length: 32,
                lowercase: true,
                uppercase: false,
                digits: false,
                symbols: false
            ))
        #expect(pw == "eexvvnlecbqmsrlpxgopjvhhwtyggkkt")
    }

    @Test("password(stripe.com, 16) matches TypeScript")
    func pwStripe16() {
        let seed = Seed.mnemonicToSeed(Self.M24)
        let pw = Seed.derivePassword(seed: seed, site: "stripe.com",
            options: DerivePasswordOptions(length: 16))
        #expect(pw == "tmF<:3_WCO#;71rL")
    }
}
